package project.trackingApp.mapper.hellmann

object HellmannFields {
    const val STATUS = "Status"
    const val HOUSE_AWB = "House AWB"
    const val SHIPPER_NAME = "Shipper Name"
    const val SHIPPER_COUNTRY = "Shipper Country"
    const val CONSIGNEE_NAME = "Consignee Name"
    const val CONSIGNEE_COUNTRY = "Consignee Country"
    const val DEPARTURE_COUNTRY = "Departure Country"
    const val DEPARTURE_PORT = "Departure Port"
    const val DESTINATION_COUNTRY = "Destination Country"
    const val DESTINATION_PORT = "Destination Port"
    const val INCOTERM = "Incoterm"
    const val FLIGHT_NO = "Flight No"
    const val PACKAGES = "No of Packages"
    const val GROSS_WEIGHT = "Gross Weight (Kg)"
    const val CHARGEABLE_WEIGHT = "Chargeable Weight (Kg)"
    const val PICKUP_DATE = "Act. Pick Up"
    const val FLIGHT_ETD = "Flight ETD"
    const val FLIGHT_ATD = "Flight ATD"
    const val FLIGHT_ETA = "Flight ETA"
    const val FLIGHT_ATA = "Flight ATA"
    const val ACT_DELIVERY = "Act. Delivery"
}
